version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kokoa
      POSTGRES_DB: kokoa
      POSTGRES_PASSWORD: kokoa
    volumes:
      - ./assets/db/init.sql:/docker-entrypoint-initdb.d/init.sql
